# Generated by Django 4.0.1 on 2022-03-22 12:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, editable=False, null=True, verbose_name='legacy #')),
                ('pos', models.IntegerField(blank=True, null=True, verbose_name='order position')),
                ('w', models.IntegerField(blank=True, null=True, verbose_name='width')),
                ('h', models.IntegerField(blank=True, null=True, verbose_name='height')),
                ('alt', models.CharField(blank=True, max_length=60)),
                ('fn', models.CharField(blank=True, editable=False, max_length=60, verbose_name='original filename')),
                ('hash', models.CharField(blank=True, max_length=40)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['content_type', 'object_id', 'pos'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
