# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 04:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, editable=False, null=True, verbose_name='legacy #')),
                ('pos', models.IntegerField(blank=True, null=True, verbose_name='order position')),
                ('alt', models.CharField(blank=True, max_length=60)),
                ('fn', models.CharField(blank=True, editable=False, max_length=60, verbose_name='original filename')),
                ('col', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.Collection')),
            ],
            options={
                'ordering': ['col', 'pos'],
            },
        ),
    ]
