# Generated by Django 2.0.3 on 2018-03-24 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_generic_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='col',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.Collection'),
        ),
        migrations.AlterField(
            model_name='file',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
    ]
