# Generated by Django 2.0.8 on 2018-10-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_ondelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='hash',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
